<template>
    <div>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        <h1>Gateko!!</h1>
        <br>
        
    </div>
</template>

<script>
export default {
    layout: "template"
}
</script>
